version: '3.3'

services:
  database:
    image: postgres
    container_name: gym-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=gym-db